#!/bin/bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $SCRIPT_DIR
cd ../

RAND=$(echo $RANDOM | md5 | head -c 16)

export POSTGRES_DATABASE=postgres
export POSTGRES_USERNAME=miragedb
export POSTGRES_PASSWORD=miragedb
export MONGO_DATABASE=miragedb
export MONGO_USERNAME=miragedb
export MONGO_PASSWORD=miragedb
export MONGO_AUTHSOURCE=admin

docker run -d --rm --name postgres_test_db_${RAND} \
  -p 5432:5432 \
  -e "POSTGRES_USER=${POSTGRES_USERNAME}" \
  -e "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" \
  -e "POSTGRES_DB=${POSTGRES_DATABASE}" \
  postgres

docker run -d --rm --name mongo_test_db_${RAND} \
  -p 27017:27017 \
  mongo --replSet rs0

function cleanup {
  docker stop postgres_test_db_${RAND}
  docker stop mongo_test_db_${RAND}
}

trap cleanup EXIT

until echo | docker exec --tty mongo_test_db_${RAND} mongo --eval 'quit(0)'; do sleep 1; done

docker exec --tty mongo_test_db_${RAND} mongo --eval "
  rs.initiate({
    _id: 'rs0',
    members: [{
       _id: 0,
      host: 'localhost'
    }]
  })
"

docker exec --tty mongo_test_db_${RAND} mongo admin --eval "
  db.createUser({
    user: '${MONGO_USERNAME}',
    pwd: '${MONGO_PASSWORD}',
    roles:[{
      role: 'root',
      db: 'admin'
    }]
  })
"

swift test
