#!/bin/bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $SCRIPT_DIR
cd ../

RAND=$(echo $RANDOM | md5 | head -c 16)

export POSTGRES_DATABASE=postgres
export POSTGRES_USERNAME=miragedb
export POSTGRES_PASSWORD=miragedb
export MONGO_DATABASE=miragedb
export MONGO_USERNAME=miragedb
export MONGO_PASSWORD=miragedb
export MONGO_AUTHSOURCE=admin

docker run -d --rm --name postgres_test_db_${RAND} \
  -p 5432:5432 \
  -e "POSTGRES_USER=${POSTGRES_USERNAME}" \
  -e "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" \
  -e "POSTGRES_DB=${POSTGRES_DATABASE}" \
  postgres

docker run -d --rm --name mongo_test_db_${RAND} \
  -p 27017:27017 \
  -e "MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}" \
  -e "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}" \
  -e "MONGO_INITDB_DATABASE=${MONGO_DATABASE}" \
  mongo

function cleanup {
  docker stop postgres_test_db_${RAND}
  docker stop mongo_test_db_${RAND}
}

trap cleanup EXIT

swift test
