name: Builder
on: [push, pull_request]
env:
  POSTGRES_DATABASE: postgres
  POSTGRES_USERNAME: miragedb
  POSTGRES_PASSWORD: miragedb
  MONGO_DATABASE: miragedb
  MONGO_USERNAME: miragedb
  MONGO_PASSWORD: miragedb
  MONGO_AUTHSOURCE: admin
  MONGO_REPLICA_SET: rs0
jobs:
  ubuntu_swift:
    name: ${{ matrix.swift_version }}-${{ matrix.distro }}
    container: 
      image: docker://swift:${{ matrix.swift_version }}-${{ matrix.distro }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports: 
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DATABASE }}
      redis:
        image: redis
        ports: 
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        swift_version: [5.6]
        distro: [bionic, focal]
    steps:
    - name: Start MongoDB
      uses: SusanDoggie/mongodb-action@0.0.1
      with:
        network: ${{ job.container.network }}
        host: mongo
        username: ${{ env.MONGO_USERNAME }}
        password: ${{ env.MONGO_PASSWORD }}
        database: ${{ env.MONGO_DATABASE }}
        replica_set: ${{ env.MONGO_REPLICA_SET }}
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Prepare
      run: apt-get update
    - name: Install libmongoc
      run: apt-get install -y libssl-dev
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
      env:
        POSTGRES_HOST: postgres
        REDIS_HOST: redis
        MONGO_HOST: mongo
  ubuntu_swift_nightly:
    name: nightly-${{ matrix.swift_version }}-${{ matrix.distro }}
    container:
      image: docker://swiftlang/swift:nightly-${{ matrix.swift_version }}-${{ matrix.distro }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports: 
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DATABASE }}
      redis:
        image: redis
        ports: 
          - 6379:6379
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        swift_version: [main]
        distro: [bionic, focal]
    steps:
    - name: Start MongoDB
      uses: SusanDoggie/mongodb-action@0.0.1
      with:
        network: ${{ job.container.network }}
        host: mongo
        username: ${{ env.MONGO_USERNAME }}
        password: ${{ env.MONGO_PASSWORD }}
        database: ${{ env.MONGO_DATABASE }}
        replica_set: ${{ env.MONGO_REPLICA_SET }}
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Prepare
      run: apt-get update
    - name: Install libmongoc
      run: apt-get install -y libssl-dev
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
      env:
        POSTGRES_HOST: postgres
        REDIS_HOST: redis
        MONGO_HOST: mongo